name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: npm ci
      - name: Test
        env:
          DISPLAY: ':99'
        run: |
          Xvfb :99 -screen 0 1920x1080x24 > /dev/null 2>&1 &
          npm test
